import type { Appointment } from "@/types";

// Using ISO date strings (yyyy-MM-dd) so they can be parsed reliably for the calendar view.
// Dates are centered around "today" (Jul 11, 2026) so the date-strip / Today's Schedule show data.
export const appointmentsMock: Appointment[] = [
  {
    id: "apt-1",
    patientId: "p-1",
    patientName: "Sara Malik",
    doctorId: "d-1",
    doctorName: "Ayesha Khan",
    date: "2026-07-11",
    time: "10:30 AM",
    status: "scheduled",
    visitType: "consultation",
    reason: "Follow-up consultation",
  },
  {
    id: "apt-2",
    patientId: "p-2",
    patientName: "Bilal Ahmed",
    doctorId: "d-2",
    doctorName: "Usman Tariq",
    date: "2026-07-11",
    time: "11:15 AM",
    status: "scheduled",
    visitType: "walk-in",
    reason: "Routine checkup",
  },
  {
    id: "apt-3",
    patientId: "p-3",
    patientName: "Hina Farooq",
    doctorId: "d-3",
    doctorName: "Fatima Noor",
    date: "2026-07-11",
    time: "12:00 PM",
    status: "completed",
    visitType: "walk-in",
    reason: "Skin allergy",
  },
  {
    id: "apt-4",
    patientId: "p-4",
    patientName: "Ali Raza",
    doctorId: "d-3",
    doctorName: "Fatima Noor",
    date: "2026-07-11",
    time: "01:30 PM",
    status: "cancelled",
    visitType: "consultation",
    reason: "Vaccination",
  },
  {
    id: "apt-5",
    patientId: "p-5",
    patientName: "Zainab Sheikh",
    doctorId: "d-5",
    doctorName: "Sadia Malik",
    date: "2026-07-12",
    time: "09:00 AM",
    status: "scheduled",
    visitType: "consultation",
    reason: "Migraine review",
  },
  {
    id: "apt-6",
    patientId: "p-6",
    patientName: "Usman Ghani",
    doctorId: "d-1",
    doctorName: "Ayesha Khan",
    date: "2026-07-12",
    time: "10:00 AM",
    status: "scheduled",
    visitType: "walk-in",
    reason: "Blood pressure review",
  },
  {
    id: "apt-7",
    patientId: "p-7",
    patientName: "Mahnoor Iqbal",
    doctorId: "d-4",
    doctorName: "Hamza Sheikh",
    date: "2026-07-13",
    time: "02:00 PM",
    status: "no-show",
    visitType: "consultation",
    reason: "Acne consultation",
  },
  {
    id: "apt-8",
    patientId: "p-1",
    patientName: "Sara Malik",
    doctorId: "d-2",
    doctorName: "Usman Tariq",
    date: "2026-07-14",
    time: "11:00 AM",
    status: "scheduled",
    visitType: "walk-in",
    reason: "Knee pain assessment",
  },
  {
    id: "apt-9",
    patientId: "p-2",
    patientName: "Bilal Ahmed",
    doctorId: "d-1",
    doctorName: "Ayesha Khan",
    date: "2026-07-08",
    time: "03:00 PM",
    status: "completed",
    visitType: "consultation",
    reason: "Cardiac screening",
  },
  {
    id: "apt-10",
    patientId: "p-3",
    patientName: "Hina Farooq",
    doctorId: "d-6",
    doctorName: "Omar Farooq",
    date: "2026-07-07",
    time: "09:30 AM",
    status: "completed",
    visitType: "walk-in",
    reason: "General checkup",
  },
];

export const TIME_SLOTS = [
  "09:00 AM",
  "09:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "01:00 PM",
  "01:30 PM",
  "02:00 PM",
  "02:30 PM",
  "03:00 PM",
  "03:30 PM",
  "04:00 PM",
];