import type { Staff } from "@/types";

export const staffMock: Staff[] = [
  {
    id: "st-1",
    fullName: "Nadia Yousaf",
    role: "Head Nurse",
    department: "Nursing",
    email: "nadia.yousaf@clinic.com",
    phone: "+92 300 1112223",
    status: "active",
    joinedOn: "Jan 2022",
  },
  {
    id: "st-2",
    fullName: "Kamran Sheikh",
    role: "Lab Technician",
    department: "Laboratory",
    email: "kamran.sheikh@clinic.com",
    phone: "+92 301 2223334",
    status: "active",
    joinedOn: "Mar 2023",
  },
  {
    id: "st-3",
    fullName: "Ayesha Riaz",
    role: "Receptionist",
    department: "Front Desk",
    email: "ayesha.riaz@clinic.com",
    phone: "+92 302 3334445",
    status: "active",
    joinedOn: "Jun 2021",
  },
  {
    id: "st-4",
    fullName: "Farhan Malik",
    role: "Pharmacist",
    department: "Pharmacy",
    email: "farhan.malik@clinic.com",
    phone: "+92 303 4445556",
    status: "inactive",
    joinedOn: "Sep 2020",
  },
  {
    id: "st-5",
    fullName: "Sana Aslam",
    role: "Nurse",
    department: "Nursing",
    email: "sana.aslam@clinic.com",
    phone: "+92 304 5556667",
    status: "active",
    joinedOn: "Nov 2023",
  },
  {
    id: "st-6",
    fullName: "Bilal Qureshi",
    role: "Billing Clerk",
    department: "Administration",
    email: "bilal.qureshi@clinic.com",
    phone: "+92 305 6667778",
    status: "active",
    joinedOn: "Feb 2024",
  },
];
